[package]
name = "phrases"
version = "0.1.0"
edition = "2021"
authors = ["CodingCoffee"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
greetings = { path = "greetings" }
